/*  
	PROCEDURE NHẬP VÀO NGÀY ĐẦU KỲ VÀ NGÀY CUỐI KỲ
	=> TRẢ VỀ KẾT QUẢ BÁO CÁO TÍN DỤNG TRONG KỲ ĐÃ CHỌN
	GỒM CÁC THÔNG TIN VỀ:
		- SỐ LƯỢNG KHOẢN VAY
		- SỐ TIỀN GIẢI NGÂN
		- SỐ KHÁCH HÀNG
		- DƯ NỢ GỐC
*/
CREATE PROC BAOCAO_TINDUNG 
	@NGAY_BAT_DAU DATE, 
	@NGAY_KET_THUC DATE
AS
BEGIN
	--------------------------------------------------------------------------------
	-- 1. KHAI BÁO BIẾN DỮ LIỆU --
	DECLARE @SO_KHOANVAY_DAUKY INT
	DECLARE @SO_KHOANVAY_PS INT
	DECLARE @SO_KHOANVAY_GIAM INT
	DECLARE @SO_KHOANVAY_CUOIKY INT

	DECLARE @SOTIEN_GIAINGAN_DAUKY DECIMAL(18, 2)
	DECLARE @SOTIEN_GIAINGAN_PS DECIMAL(18, 2)
	DECLARE @SOTIEN_GIAINGAN_GIAM DECIMAL(18, 2)
	DECLARE @SOTIEN_GIAINGAN_CUOIKY DECIMAL(18, 2)

	DECLARE @SO_KH_DAUKY INT
	DECLARE @SO_KH_PS INT
	DECLARE @SO_KH_GIAM INT
	DECLARE @SO_KH_CUOIKY INT

	DECLARE @DU_NO_GOC_DAUKY DECIMAL(18, 2)
	DECLARE @DU_NO_GOC_PS DECIMAL(18, 2)
	DECLARE @DU_NO_GOC_GIAM DECIMAL(18, 2)
	DECLARE @DU_NO_GOC_CUOIKY DECIMAL(18, 2)

	--------------------------------------------------------------------------------
	-- 2. TẠO BẢNG TẠM TỔNG HỢP DỮ LIỆU THEO MÃ HỢP ĐỒNG TÍN DỤNG --
	SELECT *
	INTO #ALL_DATA
	---- 2.1 DỮ LIỆU ĐẦU KỲ ---- 
	FROM (
		SELECT	
				A.MA_HOPDONG_TINDUNG AS MA_HD_DAUKY, 
				B.MA_KHACHHANG AS MA_KH_DAUKY, 
				SOTIEN_DAUKY AS DU_NO_DAUKY, 
				SOTIEN AS SOTIEN_GIAINGAN_DAUKY
		FROM	KEHOACH_TRANO A
				LEFT JOIN	HOPDONG_TINDUNG B ON A.MA_HOPDONG_TINDUNG = B.MA_HOPDONG_TINDUNG
		WHERE	NGAY_DAUKY <= @NGAY_BAT_DAU
				AND NGAY_CUOIKY > @NGAY_BAT_DAU
	) AS TB_DAUKY 

	---- 2.2 DỮ LIỆU PHÁT SINH TRONG KỲ -- 
	FULL JOIN (
		SELECT	
				MA_HOPDONG_TINDUNG AS MA_HD_PS, 
				MA_KHACHHANG AS MA_KH_PS, 
				SOTIEN AS SOTIEN_GIAINGAN_PS
		FROM	HOPDONG_TINDUNG
		WHERE	NGAY_GIAINGAN > @NGAY_BAT_DAU
				AND NGAY_GIAINGAN <= @NGAY_KET_THUC
	) TB_PHATSINH
				ON TB_DAUKY.MA_HD_DAUKY = TB_PHATSINH.MA_HD_PS

	---- 2.3 DỮ LIỆU HỢP ĐỒNG TÍN DỤNG ĐÁO HẠN TRONG KỲ --
	LEFT JOIN (
		SELECT	MA_HOPDONG_TINDUNG AS MA_HD_DAOHAN,
				MA_KHACHHANG AS MA_KH_DAOHAN,
				SOTIEN AS SOTIEN_GIAINGAN_DAOHAN
		FROM	HOPDONG_TINDUNG
		WHERE	NGAY_DAOHAN > @NGAY_BAT_DAU
				AND NGAY_DAOHAN <= @NGAY_KET_THUC
	) TB_DAOHAN ON TB_DAOHAN.MA_HD_DAOHAN = COALESCE(TB_DAUKY.MA_HD_DAUKY, TB_PHATSINH.MA_HD_PS)

	---- 2.4 DỮ LIỆU DƯ NỢ GIẢM TRONG KỲ --
	LEFT JOIN (
		SELECT	A.MA_HOPDONG_TINDUNG AS MA_HD_TRANO,
				SUM(SOTIEN_GOC) AS SO_TIEN_TRANO 
		FROM	KEHOACH_TRANO A
				LEFT JOIN	HOPDONG_TINDUNG B ON A.MA_HOPDONG_TINDUNG = B.MA_HOPDONG_TINDUNG
		WHERE	NGAY_CUOIKY > @NGAY_BAT_DAU
				AND NGAY_CUOIKY <= @NGAY_KET_THUC
		GROUP BY A.MA_HOPDONG_TINDUNG
	) TB_TRANO ON TB_TRANO.MA_HD_TRANO = COALESCE(TB_DAUKY.MA_HD_DAUKY, TB_PHATSINH.MA_HD_PS)

	---- 2.5 DỮ LIỆU CUỐI KỲ --
	LEFT JOIN (
		SELECT	
				A.MA_HOPDONG_TINDUNG AS MA_HD_CUOIKY, 
				B.MA_KHACHHANG AS MA_KH_CUOIKY, 
				SOTIEN_DAUKY AS DU_NO_CUOIKY, 
				SOTIEN AS SOTIEN_GIAINGAN_CUOIKY
		FROM	KEHOACH_TRANO A
				LEFT JOIN	HOPDONG_TINDUNG B ON A.MA_HOPDONG_TINDUNG = B.MA_HOPDONG_TINDUNG
		WHERE	NGAY_DAUKY <= @NGAY_KET_THUC
				AND NGAY_CUOIKY > @NGAY_KET_THUC
	) TB_CUOIKY ON TB_CUOIKY.MA_HD_CUOIKY = COALESCE(TB_DAUKY.MA_HD_DAUKY, TB_PHATSINH.MA_HD_PS)

	---- 2.6 GÁN CÁC BIẾN DỮ LIỆU VỀ SỐ KHOẢN VAY, SỐ TIỀN GIẢI NGÂN, DƯ NỢ GỐC --
	SET @SO_KHOANVAY_DAUKY = (SELECT COUNT(MA_HD_DAUKY) FROM #ALL_DATA)
	SET @SO_KHOANVAY_PS = (SELECT COUNT(MA_HD_PS) FROM #ALL_DATA)
	SET @SO_KHOANVAY_GIAM = (SELECT COUNT(MA_HD_DAOHAN) FROM #ALL_DATA)
	SET @SO_KHOANVAY_CUOIKY = (SELECT COUNT(MA_HD_CUOIKY) FROM #ALL_DATA)

	SET @SOTIEN_GIAINGAN_DAUKY = (SELECT SUM(SOTIEN_GIAINGAN_DAUKY) FROM #ALL_DATA)
	SET @SOTIEN_GIAINGAN_PS = (SELECT SUM(SOTIEN_GIAINGAN_PS) FROM #ALL_DATA)
	SET @SOTIEN_GIAINGAN_GIAM = (SELECT SUM(SOTIEN_GIAINGAN_DAOHAN) FROM #ALL_DATA)
	SET @SOTIEN_GIAINGAN_CUOIKY = (SELECT SUM(SOTIEN_GIAINGAN_CUOIKY) FROM #ALL_DATA)

	SET @DU_NO_GOC_DAUKY = (SELECT SUM(DU_NO_DAUKY) FROM #ALL_DATA)
	SET @DU_NO_GOC_PS = (SELECT SUM(SOTIEN_GIAINGAN_PS) FROM #ALL_DATA)
	SET @DU_NO_GOC_GIAM = (SELECT SUM(SO_TIEN_TRANO) FROM #ALL_DATA)
	SET @DU_NO_GOC_CUOIKY = (SELECT SUM(DU_NO_CUOIKY) FROM #ALL_DATA)

	--------------------------------------------------------------------------------
	-- 3. TẠO BẢNG TẠM TỔNG HỢP DỮ LIỆU THEO MÃ KHÁCH HÀNG --
	SELECT 
			MA_KH_DAUKY, 
			MA_KH_PS, 
			MA_KH_DAOHAN,
			MA_KH_CUOIKY
	INTO #ALL_DATA_THEO_KHACH_HANG
	---- 3.1 KHÁCH HÀNG ĐẦU KỲ
	FROM	(
		SELECT MA_KH_DAUKY 
		FROM #ALL_DATA
		GROUP BY MA_KH_DAUKY
	) TB_DAUKY

	---- 3.2 KHÁCH HÀNG PHÁT SINH
	FULL JOIN (
		SELECT MA_KH_PS
		FROM #ALL_DATA
		GROUP BY MA_KH_PS
	) TB_PS ON TB_PS.MA_KH_PS = TB_DAUKY.MA_KH_DAUKY

	---- 3.3 KHÁCH HÀNG GIẢM
	LEFT JOIN (
		SELECT MA_KH_DAOHAN 
		FROM #ALL_DATA
		GROUP BY MA_KH_DAOHAN
	) TB_GIAM ON TB_GIAM.MA_KH_DAOHAN = COALESCE(TB_PS.MA_KH_PS, TB_DAUKY.MA_KH_DAUKY)

	---- 3.4 KHÁCH HÀNG CUỐI KỲ
	LEFT JOIN (
		SELECT MA_KH_CUOIKY
		FROM #ALL_DATA
		GROUP BY MA_KH_CUOIKY
	) TB_CUOIKY ON TB_CUOIKY.MA_KH_CUOIKY = COALESCE(TB_PS.MA_KH_PS, TB_DAUKY.MA_KH_DAUKY)
	

	---- 3.5 SET GIÁ TRỊ CHO CÁC BIẾN
	SET @SO_KH_DAUKY = (SELECT COUNT(MA_KH_DAUKY) FROM #ALL_DATA_THEO_KHACH_HANG)
	SET @SO_KH_PS = (SELECT COUNT(MA_KH_PS) FROM #ALL_DATA_THEO_KHACH_HANG WHERE MA_KH_DAUKY IS NULL)
	SET @SO_KH_GIAM = (SELECT COUNT(MA_KH_DAOHAN) FROM #ALL_DATA_THEO_KHACH_HANG WHERE MA_KH_CUOIKY IS NULL)
	SET @SO_KH_CUOIKY = (SELECT COUNT(MA_KH_CUOIKY) FROM #ALL_DATA_THEO_KHACH_HANG)

	--------------------------------------------------------------------------------
	-- 4. XUẤT DỮ LIỆU BÁO CÁO
		SELECT	N'Số khoản vay' AS "Nội dung",
				@SO_KHOANVAY_DAUKY AS "Đầu kỳ", 
				@SO_KHOANVAY_PS "Phát sinh tăng",
				@SO_KHOANVAY_GIAM "Phát sinh giảm",
				@SO_KHOANVAY_CUOIKY "Cuối kỳ"

UNION SELECT	N'Tổng tiền giải ngân',
				@SOTIEN_GIAINGAN_DAUKY, 
				@SOTIEN_GIAINGAN_PS, 
				@SOTIEN_GIAINGAN_GIAM,
				@SOTIEN_GIAINGAN_CUOIKY

UNION SELECT	N'Số lượng khách hàng',
				@SO_KH_DAUKY,
				@SO_KH_PS,
				@SO_KH_GIAM, 
				@SO_KH_CUOIKY

UNION SELECT	N'Dư nợ gốc',
				@DU_NO_GOC_DAUKY,
				@DU_NO_GOC_PS,
				@DU_NO_GOC_GIAM, 
				@DU_NO_GOC_CUOIKY

END;

-- EXEC BAOCAO_TINDUNG '2022-12-31', '2025-12-31'



---------------------------------------------------------------------
---------------------------------------------------------------------
/*
	PROCEDURE NHẬP VÀO SỐ TỰ NHIÊN @N, NĂM @Y, 
	=> TRẢ VỀ TOP N HỢP ĐỒNG TÍN DỤNG CÓ GIÁ TRỊ LỚN NHẤT TRONG NĂM @Y
	CÁC CỘT DỮ LIỆU GỒM:
		- STT
		- MÃ HỢP ĐỒNG
		- NGÀY TẠO 
		- TÊN KHÁCH HÀNG
		- SỐ TIỀN
*/
CREATE PROC TOP_HOPDONG_TINDUNG
	@N INT, 
	@Y INT
AS
BEGIN
	SELECT *
	FROM (
		SELECT	
				RANK () OVER(ORDER BY SOTIEN DESC) "Số thứ tự",
				MA_HOPDONG_TINDUNG "Mã hợp đồng", 
				NGAY_GIAINGAN "Ngày giải ngân", 
				B.TEN_KHACHHANG "Tên khách hàng",
				SOTIEN "Số tiền"
		FROM	HOPDONG_TINDUNG A
				LEFT JOIN KHACHHANG B ON A.MA_KHACHHANG = B.MA_KHACHHANG
		WHERE	YEAR(NGAY_GIAINGAN) = @Y
	) TB
	WHERE "Số thứ tự" <= @N
END;

-- EXEC TOP_HOPDONG_TINDUNG 3, 2022



---------------------------------------------------------------------
---------------------------------------------------------------------
/*
	PROCEDURE NHẬP VÀO ĐẦU VÀO LÀ MÃ KHU VỰC, NĂM
	=> TRẢ VỀ DANH SÁCH HỢP ĐỒNG TẠO MỚI CỦA KHU VỰC TRONG NĂM ĐÓ
*/
CREATE PROC DANHSACH_HOPDONG_TINDUNG_KHUVUC
	@MA_KHU_VUC VARCHAR(10),
	@YEAR INT 
AS
BEGIN
	SELECT	RANK () OVER(ORDER BY SOTIEN DESC) "Số thứ tự",
			MA_HOPDONG_TINDUNG "Mã hợp đồng", 
			NGAY_GIAINGAN "Ngày giải ngân", 
			B.TEN_KHACHHANG "Tên khách hàng",
			SOTIEN "Số tiền"
	FROM	HOPDONG_TINDUNG		A
			LEFT JOIN KHACHHANG	B ON A.MA_KHACHHANG = B.MA_KHACHHANG
			LEFT JOIN CHINHANH	C ON C.MA_CHINHANH = B.MA_CHINHANH
			LEFT JOIN KHUVUC	D ON D.MA_KHUVUC = C.MA_KHUVUC
	WHERE	D.MA_KHUVUC = @MA_KHU_VUC
			AND YEAR(NGAY_GIAINGAN) = @YEAR
END;

-- EXEC DANHSACH_HOPDONG_TINDUNG_KHUVUC 'A01', 2022




---------------------------------------------------------------------
---------------------------------------------------------------------
/* 
	PROCEDURE NHẬP GIÁ TRỊ ĐẦU VÀO LÀ NĂM
	TRẢ VỀ BÁO CÁO SỐ LƯỢNG HỢP ĐỒNG TÍN DỤNG PHÁT SINH THEO CÁC TIÊU CHÍ
*/
CREATE PROC BAO_CAO_TINDUNG_CAC_TIEUCHI
@YEAR INT
AS
BEGIN
	-- TẠO CÁC BẢNG TẠM LƯU DỮ LIỆU --
	-- 1. MỤC ĐÍCH CẤP TÍN DỤNG
	SELECT		TEN_MUCDICH_CAP1 "Tiêu chí",
				SUM(COALESCE("Số hợp đồng tín dụng", 0)) "Số hợp đồng tín dụng", 
				SUM(COALESCE("Số tiền giải ngân", 0)) "Số tiền giải ngân"
	INTO #MUCDICH_TINDUNG
	FROM MUCDICH_CAPTINDUNG A
	LEFT JOIN (
		SELECT	MA_MUCDICH_CAPTD,
				COUNT(MA_HOPDONG_TINDUNG) "Số hợp đồng tín dụng", 
				SUM(SOTIEN) "Số tiền giải ngân"
		FROM	HOPDONG_TINDUNG
		WHERE	YEAR(NGAY_GIAINGAN) = @YEAR 
		GROUP BY MA_MUCDICH_CAPTD
	) TB_TINDUNG 
			ON A.MA_MUCDICH_CAPTD = TB_TINDUNG.MA_MUCDICH_CAPTD
	GROUP BY 
			TEN_MUCDICH_CAP1

	-------------------------------
	-- 2. HÌNH THỨC CẤP TÍN DỤNG --
	SELECT		TEN_HINHTHUC_CAP1 "Tiêu chí",
				SUM(COALESCE("Số hợp đồng tín dụng", 0)) "Số hợp đồng tín dụng", 
				SUM(COALESCE("Số tiền giải ngân", 0)) "Số tiền giải ngân"
	INTO #HINHTHUC_TINDUNG
	FROM HINHTHUC_CAPTINDUNG A
	LEFT JOIN (
		SELECT	MA_HINHTHUC_CAPTD,
				COUNT(MA_HOPDONG_TINDUNG) "Số hợp đồng tín dụng", 
				SUM(SOTIEN) "Số tiền giải ngân"
		FROM	HOPDONG_TINDUNG
		WHERE	YEAR(NGAY_GIAINGAN) = @YEAR 
		GROUP BY MA_HINHTHUC_CAPTD
	) TB_TINDUNG 
			ON A.MA_HINHTHUC_CAPTD = TB_TINDUNG.MA_HINHTHUC_CAPTD
	GROUP BY 
			TEN_HINHTHUC_CAP1

--- 3. XUẤT BẢNG BÁO CÁO

SELECT	"Tiêu chí",
		"Số hợp đồng tín dụng",
		"Số tiền giải ngân"
FROM (  
		-- Tổng dữ liệu theo mục đích cấp tín dụng
		SELECT	N'Mục đích cấp tín dụng' AS "Tiêu chí",
				SUM("Số hợp đồng tín dụng") AS "Số hợp đồng tín dụng",
				SUM("Số tiền giải ngân") AS "Số tiền giải ngân",
				1 AS "Sorter"
		FROM #MUCDICH_TINDUNG

	UNION 
		SELECT 
				CONCAT(ROW_NUMBER() OVER(ORDER BY "Số tiền giải ngân" DESC), '-', "Tiêu chí"), 
				-- "Tiêu chí",
				"Số hợp đồng tín dụng",
				"Số tiền giải ngân",
				2 AS "Sorter"
		FROM #MUCDICH_TINDUNG

	UNION 
		-- Tổng dữ liệu theo hình thức cấp tín dụng
		SELECT	N'Hình thức cấp tín dụng' AS "Tiêu chí",
				SUM("Số hợp đồng tín dụng") AS "Số hợp đồng tín dụng",
				SUM("Số tiền giải ngân") AS "Số tiền giải ngân",
				3 AS "Sorter"
		FROM #HINHTHUC_TINDUNG

	UNION 
		SELECT 
				CONCAT(ROW_NUMBER() OVER(ORDER BY "Số tiền giải ngân" DESC), '-', "Tiêu chí"), 
				-- "Tiêu chí",
				"Số hợp đồng tín dụng",
				"Số tiền giải ngân",
				4 AS "Sorter"
		FROM #HINHTHUC_TINDUNG
) DATA
ORDER BY Sorter

END;

-- EXEC BAO_CAO_TINDUNG_CAC_TIEUCHI 2022
