-- 1. SỐ KHOẢN TIẾT KIỆM
-- 2. SỐ LƯỢNG KHÁCH HÀNG
-- 3. TỔNG TIỀN TIẾT KIỆM

CREATE PROC BAO_CAO_HUY_DONG_VON 
	@NGAY_BAT_DAU DATE, 
	@NGAY_KET_THUC DATE
AS
BEGIN
	-- 1. KHAI BÁO BIẾN -------
	---- SỐ KHOẢN TIẾT KIỆM
	DECLARE @SO_KHOAN_TK_DAU_KY INT
	DECLARE @SO_KHOAN_TK_MO_MOI INT
	DECLARE @SO_KHOAN_TK_TAT_TOAN INT
	DECLARE @SO_KHOAN_TK_CUOI_KY INT
	---- SỐ KHÁCH HÀNG
	DECLARE @SO_KH_DAU_KY INT
	DECLARE @SO_KH_MO_MOI INT
	DECLARE @SO_KH_TAT_TOAN INT
	DECLARE @SO_KH_CUOI_KY INT
	---- SỐ TIỀN TIẾT KIỆM
	DECLARE @SO_TIEN_TK_DAU_KY DECIMAL(18,2)
	DECLARE @SO_TIEN_TK_MO_MOI DECIMAL(18,2)
	DECLARE @SO_TIEN_TK_TAT_TOAN DECIMAL(18,2)
	DECLARE @SO_TIEN_TK_CUOI_KY DECIMAL(18,2)

	-- 2. LẤY CÁC DỮ LIỆU VỀ SỐ KHOẢN VÀ SỐ TIỀN TIẾT KIỆM ----
	---- DỮ LIỆU SỐ KHOẢN TIẾT KIỆM VÀ SỐ TIỀN ĐẦU KỲ --
	SET @SO_KHOAN_TK_DAU_KY = (	SELECT	COUNT(MA_TAIKHOAN_TIETKIEM)
								FROM	TIENGUI_TIETKIEM
								WHERE	(NGAY_GUI <= @NGAY_BAT_DAU AND TRANG_THAI = 0)
										OR (NGAY_GUI <= @NGAY_BAT_DAU AND TRANG_THAI = 1 AND NGAY_DENHAN > @NGAY_BAT_DAU)
							)
	SET @SO_TIEN_TK_DAU_KY = (	SELECT	SUM(SOTIEN)
								FROM	TIENGUI_TIETKIEM
								WHERE	(NGAY_GUI <= @NGAY_BAT_DAU AND TRANG_THAI = 0)
										OR (NGAY_GUI <= @NGAY_BAT_DAU AND TRANG_THAI = 1 AND NGAY_DENHAN > @NGAY_BAT_DAU)
							)

	-- DỮ LIỆU SỐ KHOẢN TIẾT KIỆM VÀ SỐ TIỀN MỞ MỚI --
	SET @SO_KHOAN_TK_MO_MOI = (	SELECT COUNT(MA_TAIKHOAN_TIETKIEM)
              								FROM TIENGUI_TIETKIEM
              								WHERE 
              									NGAY_GUI > @NGAY_BAT_DAU
              									AND NGAY_GUI <= @NGAY_KET_THUC)
	SET @SO_TIEN_TK_MO_MOI =  ( SELECT SUM(SOTIEN)
            								  FROM TIENGUI_TIETKIEM
            								  WHERE 
              									NGAY_GUI > @NGAY_BAT_DAU
              									AND NGAY_GUI <= @NGAY_KET_THUC)

	-- DỮ LIỆU SỐ KHOẢN TIẾT KIỆM VÀ SỐ TIỀN TẤT TOÁN --
	SET @SO_KHOAN_TK_TAT_TOAN = ( SELECT COUNT(MA_TAIKHOAN_TIETKIEM)
              									FROM TIENGUI_TIETKIEM
              									WHERE 
              										NGAY_DENHAN > @NGAY_BAT_DAU
              										AND NGAY_DENHAN <= @NGAY_KET_THUC)
	SET @SO_TIEN_TK_TAT_TOAN = (SELECT	SUM(SOTIEN)
              								FROM	TIENGUI_TIETKIEM
              								WHERE 
                                NGAY_DENHAN > @NGAY_BAT_DAU
                                AND NGAY_DENHAN <= @NGAY_KET_THUC)

	-- DỮ LIỆU SỐ KHOẢN TIẾT KIỆM VÀ SỐ TIỀN CUỐI KỲ --
	SET @SO_KHOAN_TK_CUOI_KY = (SELECT	COUNT(MA_TAIKHOAN_TIETKIEM)
              								FROM	TIENGUI_TIETKIEM
              								WHERE	(NGAY_GUI <= @NGAY_KET_THUC AND TRANG_THAI = 0)
              										OR (NGAY_GUI <= @NGAY_KET_THUC AND TRANG_THAI = 1 AND NGAY_DENHAN > @NGAY_KET_THUC))
	SET @SO_TIEN_TK_CUOI_KY =  (SELECT	SUM(SOTIEN)
              								FROM	TIENGUI_TIETKIEM
              								WHERE	(NGAY_GUI <= @NGAY_KET_THUC AND TRANG_THAI = 0)
              										OR (NGAY_GUI <= @NGAY_KET_THUC AND TRANG_THAI = 1 AND NGAY_DENHAN > @NGAY_KET_THUC))


	-- 3. DỮ LIỆU SỐ LƯỢNG KHÁCH HÀNG ----
	---- TẠO TEMP TABLE TỔNG HỢP DỮ LIỆU THEO KHÁCH HÀNG --
	SELECT 
  			KHACH_HANG_DAU_KY,
  			KHACH_HANG_PHAT_SINH,
  			KHACH_HANG_TAT_TOAN ,
  			KHACH_HANG_CUOI_KY 
	INTO	#TEMP_KHACHHANG
	FROM (
		SELECT	MA_KHACHHANG "KHACH_HANG_DAU_KY"
		FROM	TIENGUI_TIETKIEM
		WHERE	(NGAY_GUI <= @NGAY_BAT_DAU AND TRANG_THAI = 0)
				OR (NGAY_GUI <= @NGAY_BAT_DAU AND TRANG_THAI = 1 AND NGAY_DENHAN > @NGAY_BAT_DAU)
		GROUP BY MA_KHACHHANG
	) DAU_KY 

	FULL JOIN (
		SELECT	MA_KHACHHANG "KHACH_HANG_PHAT_SINH"
		FROM	TIENGUI_TIETKIEM
		WHERE	NGAY_GUI > @NGAY_BAT_DAU
				AND NGAY_GUI <= @NGAY_KET_THUC
		GROUP BY MA_KHACHHANG
	) PHAT_SINH
		ON DAU_KY.KHACH_HANG_DAU_KY = PHAT_SINH.KHACH_HANG_PHAT_SINH

	FULL JOIN (
		SELECT	MA_KHACHHANG "KHACH_HANG_TAT_TOAN"
		FROM	TIENGUI_TIETKIEM
		WHERE	NGAY_DENHAN > @NGAY_BAT_DAU
				AND NGAY_DENHAN <= @NGAY_KET_THUC
		GROUP BY MA_KHACHHANG
	) TAT_TOAN 
		ON TAT_TOAN.KHACH_HANG_TAT_TOAN = COALESCE(DAU_KY.KHACH_HANG_DAU_KY, PHAT_SINH.KHACH_HANG_PHAT_SINH)

	FULL JOIN (
		SELECT	MA_KHACHHANG "KHACH_HANG_CUOI_KY"
		FROM	TIENGUI_TIETKIEM
		WHERE	(NGAY_GUI <= @NGAY_KET_THUC AND TRANG_THAI = 0)
				OR (NGAY_GUI <= @NGAY_KET_THUC AND TRANG_THAI = 1 AND NGAY_DENHAN > @NGAY_BAT_DAU)
		GROUP BY MA_KHACHHANG
	) CUOI_KY 
		ON CUOI_KY.KHACH_HANG_CUOI_KY = COALESCE(DAU_KY.KHACH_HANG_DAU_KY, PHAT_SINH.KHACH_HANG_PHAT_SINH)

	-- Update các dữ liệu vào các biến
	SET @SO_KH_DAU_KY = (SELECT COUNT(KHACH_HANG_DAU_KY) FROM #TEMP_KHACHHANG)
	SET @SO_KH_MO_MOI = (
		SELECT COUNT(KHACH_HANG_PHAT_SINH) 
		FROM #TEMP_KHACHHANG
		WHERE KHACH_HANG_DAU_KY IS NULL
	)
	SET @SO_KH_TAT_TOAN = (
		SELECT COUNT(KHACH_HANG_TAT_TOAN) 
		FROM #TEMP_KHACHHANG
		WHERE KHACH_HANG_CUOI_KY IS NULL
	)
	SET @SO_KH_CUOI_KY = (SELECT COUNT(KHACH_HANG_CUOI_KY) FROM #TEMP_KHACHHANG)
	DROP TABLE #TEMP_KHACHHANG


	-- 4. XUẤT DỮ LIỆU -- 
		SELECT	N'Số khoản tiết kiệm' AS "NỘI DUNG"
				, @SO_KHOAN_TK_DAU_KY "ĐẦU KỲ"
				, @SO_KHOAN_TK_MO_MOI "MỞ MỚI"
				, @SO_KHOAN_TK_TAT_TOAN "TẤT TOÁN"
				, @SO_KHOAN_TK_CUOI_KY "CUỐI KỲ"
	UNION 
		SELECT	N'Số lượng khách hàng',
				@SO_KH_DAU_KY,
				@SO_KH_MO_MOI,
				@SO_KH_TAT_TOAN,
				@SO_KH_CUOI_KY
	UNION 
		SELECT	N'Tổng tiền tiết kiệm',
				@SO_TIEN_TK_DAU_KY, 
				@SO_TIEN_TK_MO_MOI, 
				@SO_TIEN_TK_TAT_TOAN, 
				@SO_TIEN_TK_CUOI_KY
END;


-- THỰC THI PROCEDURE
EXEC BAO_CAO_HUY_DONG_VON '2023-12-31', '2024-06-30'

